// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrq6ToDsGMgYXIGABQl9cTO9IA3ilgWlE',
    appId: '1:1069298985:web:851ee07767dead9266b338',
    messagingSenderId: '1069298985',
    projectId: 'fruit-market-project',
    authDomain: 'fruit-market-project.firebaseapp.com',
    storageBucket: 'fruit-market-project.appspot.com',
    measurementId: 'G-QKLMQCDTST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzWqnQcqSNTLfY_fwRsQ0FQIao-J7PEI',
    appId: '1:1069298985:android:a265b98b5d2cb69f66b338',
    messagingSenderId: '1069298985',
    projectId: 'fruit-market-project',
    storageBucket: 'fruit-market-project.appspot.com',
  );
}
